### ISSUE TITLE
testing branch

### ISSUE THREAD

**Issue by agentmnm** [jenkie/Arduino-Pedelec-Controller#19]
maybe you should introduce a testing branch, where the latest changes can be tested until they are deemed stable. Similar to the Debian Linux version management. 

The advantage is, that people who are downloading testing know, that the firmware might contain bugs, and there is still the fall-back to stable (or master in that case, we might want to call it stable).

That way bugs will get sorted out by a broader testing-group.

Isn't that what github is all about ;)

Thanks for thinking about it!

**Comment by thomasjfox** [comment]
I think the release tagging jenkie does is a good compromise on this topic.

-> you can download a stable release based upon the tag, even as .zip file.
That's also the version the APC downloads.

Closing topic for now :)
